netfilter: nftables: add nft_parse_register_load() and use it
This new function combines the netlink register attribute parser
and the load validation function.

This update requires to replace:

	enum nft_registers      sreg:8;

in many of the expression private areas otherwise compiler complains
with:

	error: cannot take address of bit-field ‘sreg’

when passing the register field as reference.

Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>
(cherry picked from commit 4f16d25c68ec844299a4df6ecbb0234eaf88a935)
[5.4: Skipped bitwise fast init changes]
Signed-off-by: Samuel Mendoza-Jonas <samjonas@amazon.com>