netfilter: nftables: add nft_parse_register_store() and use it
This new function combines the netlink register attribute parser
and the store validation function.

This update requires to replace:

        enum nft_registers      dreg:8;

in many of the expression private areas otherwise compiler complains
with:

        error: cannot take address of bit-field ‘dreg’

when passing the register field as reference.

Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>
(cherry picked from commit 345023b0db315648ccc3c1a36aee88304a8b4d91)
[5.4: skipped bitwise_fast changes]
Signed-off-by: Samuel Mendoza-Jonas <samjonas@amazon.com>